#!/bin/sh

SESSION=$(basename $(pwd) | sed -e "s/\./_/g")

tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux attach -t $SESSION
    exit 0;
fi

tmux new-session -d -s $SESSION

tmux set-window-option -t $SESSION -g automatic-rename off
tmux new-window -t $SESSION:1 -k -n todo 'vim ~/todo.tasks; fish'
if [ -f config/environment.rb ]; then
  tmux new-window -t $SESSION:2 -n rc  'rails console'
else
  tmux new-window -t $SESSION:2 -n pry 'pry'
fi
tmux new-window -t $SESSION:3 -n vim  'vim; fish'
tmux new-window -t $SESSION:4 -n shell
if [ -f config/environment.rb ]; then
  tmux new-window -t $SESSION:6 -n rs  'rails server'
fi

tmux set-window-option -t $SESSION -g automatic-rename on
tmux select-window -t $SESSION:1
tmux attach -t $SESSION
