AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*'
  NewCops: enable

# -- [[ Layout ]] --------------------------------------------------------------

Layout/ParameterAlignment:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines_except_namespace

Layout/HashAlignment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceBeforeFirstArg:
  Enabled: true

# -- [[ Lint ]] ----------------------------------------------------------------

Lint/DeprecatedClassMethods:
  Enabled: false

# -- [[ Metrics ]] -------------------------------------------------------------

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

# -- [[ Naming ]] --------------------------------------------------------------

Naming/ConstantName:
  Enabled: true

# -- [[ Style ]] ---------------------------------------------------------------

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 15

Style/Proc:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/SymbolProc:
  Enabled: true
