local glyphs = require('testbus.glyphs')
local adapters = require('testbus.adapters')
local state = require('testbus.state')
local config = require('testbus.config')

---@class Testbus
---@field setup fun(opts: Config)
---@field start fun(fn: fun()) Initialize the state and run the function passed in argument
---@field interrupt fun() Notify that the process has stopped early
---@field redraw fun(data: table<string>) Process the list as well as the json generated by the tests
local M = {}

---- Drawer --------------------------------------------------------------------
---@enum Outcome
Outcome = {
  PASSED = 'passed',
  FAILED = 'failed',
  MIXED = 'mixed',
}
---@alias bufnr integer

---@class Report
---@field bufnr integer buffer number
---@field outcomes table<integer, table<integer,Outcome>> list of outcomes, indexed by line number
---@field diag table<vim.Diagnostic> list of diagnostics with errors

---@alias Reports table<bufnr, Report>

---@param reports Reports the state to be drawn
local draw = function(reports)
  for bufnr, report in pairs(reports) do
    vim.api.nvim_buf_clear_namespace(bufnr, state.namespace(), 0, -1)
    for lnum, outcome in pairs(report.outcomes) do
      local ok, lines = pcall(vim.api.nvim_buf_get_lines, bufnr, lnum, lnum + 1, true)
      if not ok then lines = { '' } end
      local _, col = (lines[1] or ''):find('^%s*')
      local mark = { id = lnum, virt_text_pos = 'inline', virt_text = { assert(config.markers[outcome]), { ' ', 'Normal' } } }
      pcall(vim.api.nvim_buf_set_extmark, bufnr, state.namespace(), lnum, col or 0, mark)
    end

    pcall(vim.diagnostic.set, state.namespace(), bufnr, report.diag, config.diagnostics)
    pcall(vim.diagnostic.setqflist, { title = ' tests results', namespace = state.namespace(), open = false })
  end
end
--------------------------------------------------------------------------------

---- Public interface ----------------------------------------------------------
M.setup = function(opts) config = vim.tbl_deep_extend('force', config, opts) end

M.statusline = {
  icon = function()
    return state.has_run() and (
      '󰙨 → ' .. (
        (state.error_count() > 0)
        and glyphs.number(state.error_count())
        or (config.status[state.current()] or {}).icon
      )
    ) or ''
  end,
  color = function() return (config.status[state.current()] or {}).color end,
}

M.redraw = function(data)
  local handler = state.handler()
  if not handler then return end
  local success, result = handler.handle(data, config.json_path)
  if success and result then draw(result) end
end
M.clear = state.clear

M.start = function(fn) state.start(fn, config.json_path) end
M.interrupt = function() if state.is_running() then state.stop() end end
M.is_awaiting = state.is_awaiting
M.adapters = adapters

return M
