#!/usr/bin/env bash

envfile="$HOME/.context.env"
[ -f "$envfile" ] && . "$envfile"

envfile="$HOME/.env"
[ -f "$envfile" ] && . "$envfile"

case "$CONTEXT" in
  work)
    claude
    ;;
  *)
    ollama launch claude --model "$CLAUDE_MODEL"
esac
