#!/usr/bin/env bash
# shellcheck disable=SC1090

envfile="$HOME/.context.env"
[ -f "$envfile" ] && . "$envfile"

envfile="$HOME/.env"
[ -f "$envfile" ] && . "$envfile"

case "$CONTEXT" in
  work)
    claude
    ;;
  *)
    ollama launch opencode --model "$CLAUDE_MODEL"
esac
