#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && . "$envfile"

if [ -z "$1" ]; then
  profile="$CONTEXT"
else
  profile="$1"
fi

case "$profile" in
  home)
    browser-kiosk "perso" "https://discord.com/channels/@me"
    ;;
  *)
    browser-kiosk $profile "https://discord.com/channels/@me"
    ;;
esac
