; extends

(operation (command) @keyword.git_rebase.pick (#any-of? @keyword.git_rebase.pick "p" "pick"))
(operation (command) @keyword.git_rebase.reword (#any-of? @keyword.git_rebase.reword "r" "reword"))
(operation (command) @keyword.git_rebase.edit (#any-of? @keyword.git_rebase.edit "e" "edit"))
(operation (command) @keyword.git_rebase.squash (#any-of? @keyword.git_rebase.squash "s" "squash"))
(operation (command) @keyword.git_rebase.fixup (#any-of? @keyword.git_rebase.fixup "f" "fixup"))
(operation (command) @keyword.git_rebase.exec (#any-of? @keyword.git_rebase.exec "x" "exec"))
(operation (command) @keyword.git_rebase.break (#any-of? @keyword.git_rebase.break "b" "break"))
(operation (command) @keyword.git_rebase.drop (#any-of? @keyword.git_rebase.drop "d" "drop"))
(operation (command) @keyword.git_rebase.label (#any-of? @keyword.git_rebase.label "l" "label"))
(operation (command) @keyword.git_rebase.reset (#any-of? @keyword.git_rebase.reset "t" "reset"))
(operation (command) @keyword.git_rebase.merge (#any-of? @keyword.git_rebase.merge "m" "merge"))
(operation (command) @keyword.git_rebase.update-ref (#any-of? @keyword.git_rebase.update-ref "u" "update-ref"))
(operation
  (command)
  @keyword.git_rebase.invalid
  (#not-eq? @keyword.git_rebase.invalid "p")
  (#not-eq? @keyword.git_rebase.invalid "pick")
  (#not-eq? @keyword.git_rebase.invalid "reword")
  (#not-eq? @keyword.git_rebase.invalid "e")
  (#not-eq? @keyword.git_rebase.invalid "edit")
  (#not-eq? @keyword.git_rebase.invalid "s")
  (#not-eq? @keyword.git_rebase.invalid "squash")
  (#not-eq? @keyword.git_rebase.invalid "f")
  (#not-eq? @keyword.git_rebase.invalid "fixup")
  (#not-eq? @keyword.git_rebase.invalid "x")
  (#not-eq? @keyword.git_rebase.invalid "exec")
  (#not-eq? @keyword.git_rebase.invalid "b")
  (#not-eq? @keyword.git_rebase.invalid "break")
  (#not-eq? @keyword.git_rebase.invalid "d")
  (#not-eq? @keyword.git_rebase.invalid "drop")
  (#not-eq? @keyword.git_rebase.invalid "l")
  (#not-eq? @keyword.git_rebase.invalid "label")
  (#not-eq? @keyword.git_rebase.invalid "t")
  (#not-eq? @keyword.git_rebase.invalid "reset")
  (#not-eq? @keyword.git_rebase.invalid "m")
  (#not-eq? @keyword.git_rebase.invalid "merge")
  (#not-eq? @keyword.git_rebase.invalid "u")
  (#not-eq? @keyword.git_rebase.invalid "update-ref")
  (#not-eq? @keyword.git_rebase.invalid "")
)
