return {
  'Bekaboo/dropbar.nvim',
  dependencies = { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
  opts = {
    bar = {
      padding = { left = 2, right = 1 },
    },
    sources = {
      path = {
        max_depth = 1,
      },
    },
    icons = {
      ui = {
        bar = { separator = '  ', extends = '󰇘' },
        menu = { separator = ' ', indicator = ' ' },
      },
      kinds = {
        symbols = {
          Text = ' ',
          Method = '󰡱 ',
          Function = '󰡱 ',
          Constructor = '󰡱 ',
          Field = ' ',
          Property = ' ',
          Variable = '󰀫 ',
          Constant = '󱃮 ',
          Class = ' ',
          Interface = ' ',
          Module = '󰅩 ',
          Unit = '󰺾 ',
          Value = '󰎠 ',
          Enum = ' ',
          EnumMember = ' ',
          Keyword = ' ',
          Color = '󰌁 ',
          Reference = ' ',
          File = '󰈔 ',
          Folder = ' ',
          Struct = ' ',
          Event = '󱐌 ',
          Operator = '󱓉 ',
          TypeParameter = ' ',
          Copilot = '󱨚 ',

          Array = '󰅪 ',
          BlockMappingPair = '󰅩 ',
          Boolean = ' ',
          BreakStatement = '󰙧 ',
          Call = '󰃷 ',
          CaseStatement = '󱃙 ',
          ContinueStatement = '→ ',
          Declaration = '󰙠 ',
          Delete = '󰩺 ',
          DoStatement = '󰑖 ',
          Element = '󰅩 ',
          ForStatement = '󰑖 ',
          GotoStatement = '󰁔 ',
          Identifier = '󰀫 ',
          IfStatement = '󰇉 ',
          List = '󰅪 ',
          Log = '󰦪 ',
          Lsp = ' ',
          Macro = '󰁌 ',
          MarkdownH1 = '󰉫 ',
          MarkdownH2 = '󰉬 ',
          MarkdownH3 = '󰉭 ',
          MarkdownH4 = '󰉮 ',
          MarkdownH5 = '󰉯 ',
          MarkdownH6 = '󰉰 ',
          Namespace = '󰅩 ',
          Null = '󰢤 ',
          Number = '󰎠 ',
          Object = '󰅩 ',
          Package = '󰆦 ',
          Pair = '󰅪 ',
          Regex = ' ',
          Repeat = '󰑖 ',
          Return = '󰌑 ',
          Rule = '󰅩 ',
          RuleSet = '󰅩 ',
          Scope = '󰅩 ',
          Section = '󰅩 ',
          Snippet = '󰩫 ',
          Specifier = '󰦪 ',
          Statement = '󰅩 ',
          String = '󰉾 ',
          SwitchStatement = '󰺟 ',
          Table = '󰅪 ',
          Terminal = ' ',
          Type = ' ',
          WhileStatement = '󰑖 ',
        },
      },
    },
  },
  config = function(_, opts)
    require('dropbar').setup(opts)
    local dropbar_api = require('dropbar.api')
    vim.keymap.set('n', 'gC', dropbar_api.pick, { desc = 'Pick symbols in winbar' })
  end
}
