[style.description]
foreground = { ansi = 42 }
underline = false
bold = true
italic = false

[style.command_name]
foreground = "blue"
underline = false
bold = true
italic = false

[style.example_text]
foreground = { ansi = 42 }
underline = false
bold = false
italic = false

[style.example_code]
foreground = "magenta"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "magenta"
underline = false
bold = false
italic = true

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 72

[directories]
