#!/bin/sh

if [ -z "$1" ]; then
  . ~/.context.env

  case $CONTEXT in
    home)
      CONTEXT="work"
      ;;
    *)
      CONTEXT="home"
      ;;
  esac
else
  CONTEXT="$1"
fi

echo "CONTEXT=\"$CONTEXT\"" > ~/.context.env

awesome-client <<-LUA
  require('panel').reset()
LUA
