#!/usr/bin/env sh

xrdb -query | \
  grep -E "(\*\.(color|background|foreground))|(vim\.).*" | \
  sed "s/*.//" | \
  sed "s/^\(color[0-9]*\|background\|foreground\):/#define \U\1/" | \
  sed "s/vim.background:/#define VARIANT/"

echo -n "! vim: ft=xdefaults"
