#!/bin/sh

LAUNCHER='rofi -dmenu -p "" -theme-str "#content { children: [inputbar]; }"'
LAUNCHER2='rofi -dmenu -lines 7 -i -p '
OPTIONS="Inbox\nWork\nHome\nConnect\nContinuous Improvement\nCourses\nRoll20"

input=$(eval $LAUNCHER)

if [[ -n "$input" ]]; then
  option=`echo -e $OPTIONS | $LAUNCHER2`
  if [ ${#option} -gt 0 ]; then
    case $option in
      Inbox)
        task add "$input" +inbox
        ;;
      Work)
        task add "$input" +inbox +@work
        ;;
      Home)
        task add "$input" +inbox +@home
        ;;
      Connect)
        task add "$input" +inbox +@work project:connect
        ;;
      "Continuous Improvement")
        task add "$input" project:improvements
        ;;
      Courses)
        task add "$input" project:shopping
        ;;
      Roll20)
        task add "$input" project:roll20 +@home
        ;;
      *)
        ;;
    esac
  fi
fi
