#!/bin/sh

LAUNCHER='rofi -dmenu -p "" -theme-str "#content { children: [inputbar]; }"'
LAUNCHER2='rofi -dmenu -lines 9 -i -p '
OPTIONS="Inbox\nHome\nWork\nConnect\nCSE\nManagement\nContinuous Improvement\nCourses\nRoll20"

input=$(eval $LAUNCHER)

if [[ -n "$input" ]]; then
  option=`echo -e $OPTIONS | $LAUNCHER2`
  if [ ${#option} -gt 0 ]; then
    case $option in
      Inbox)
        args="'$input' +inbox"
        ;;
      Work)
        args="'$input' +inbox +@work"
        ;;
      Home)
        args="'$input' +inbox +@home"
        ;;
      Management)
        args="'$input' +inbox +@work project:mgt"
        ;;
      Connect)
        args="'$input' +inbox +@work project:connect"
        ;;
      "Continuous Improvement")
        args="'$input' project:improvements"
        ;;
      Courses)
        args="'$input' project:shopping"
        ;;
      Roll20)
        args="'$input' project:roll20 +@home"
        ;;
      CSE)
        args="'$input' project:CSE +@work"
        ;;
      *)
        args=''
        ;;
    esac

    if [ -n "$args" ]; then
      uuid=$(task add $args | perl -pe 's|Created task (.*)\.|\1|')
      url=$(echo $input | egrep -o 'https?://[^ ]+')
      if [ -n $url ]; then
        task annotate $uuid $url
      fi
    fi
  fi
fi
