#!/bin/sh

_rofi() {
  rofi \
    -i \
    -dmenu \
    -a $1 \
    -selected-row $1 \
    -p "playlist:"
}

mpc_playlist() {
  local preselected=$(\
    mpc status -f "pos: %position%" |\
    grep pos |\
    awk ' $0 ~ /^pos:/ { print $2 - 1 } '\
  )

  local format="[[[%artist%] - [%title%]]|[%file%]"
  local selection=$(
    mpc playlist -f "%position%) $format" | \
    _rofi $preselected | \
    sed -n 's/^\([0-9]\+\)).*/\1/p'
  ) || return 1

  [ -n "$selection" ] && mpc -q play $selection
}

mpc_playlist
