#!/bin/env sh

notify-send -t 2000 'mpc' 'Loading audio to mpc...'

youtube-dl -g "$1" -f'best' | mpc add \
  && mpc play \
  && notify-send -t 2000 -i dialog-apply 'mpc' 'Finished loading audio to mpc' \
  || notify-send -t 2000 -i dialog-warning 'mpc' 'Failed loading audio to mpc'
