#!/bin/sh

mpc_add() {
  mpc clear -q
  xargs -I '{}' mpc add -q '{}' <<< "$(echo "$1" | sed "s/'/\\\\'/g")"
  mpc play
}

library=$HOME/Music/

cd "$library" || exit

path=$1

help="<b>Return</b>   <i>Play selected</i>
<b>Ctrl+i</b>   <i>cd dir</i>
<b>Ctrl+o</b>   <i>cd ..</i>
<b>Ctrl+t</b>   <i>Play current dir</i>
----
<b>Tab</b>      <i>Mark</i>"

folder=$(xrdb -get color4)

selection=$(\
  find \
    "$path"* \
    -maxdepth 0 \
    -printf "<span foreground='%y'> " \
    -exec sh -c '[ $(find "{}"/* -maxdepth 0 -type d 2> /dev/null | wc -l) -gt 0 ] && echo -n "*" || echo -n " "' \; \
    -printf " %f</span>\n" \
  | sed -e "s/<span foreground='d'>/<span foreground='$folder'>/" \
  | sed -e "s/<span foreground='f'>/<span>/" \
  | sed -e "s/&/&amp;/g" \
  | rofi \
      -dmenu \
      -markup-rows \
      -format p \
      -i \
      -p "󱍙" \
      -mesg "$help" \
      -multi-select \
      -no-history \
      -kb-custom-1 "Control+o" \
      -kb-custom-2 "Control+i" \
      -kb-custom-3 "Control+t" \
      -kb-accept-alt "Tab" \
      -kb-element-next ""
)
rofi_signal=$?

selection=$(awk -F' ' '{print substr($0,5)}' <<< $selection)

list=$(sed -e "s#^#$path#" <<< $selection)

case $rofi_signal in
  10)
    target="$(readlink -f "$path/..")/"
    # We do not want to navigate “before” the library in the file tree
    if [ $(wc -c <<< "$target") -ge $(wc -c <<< $library) ]; then
      $0 "$(sed -e "s#$library##" <<< "$target")"
    else
      $0
    fi
    ;;
  11)
    [ -n "$selection" ] && $0 "$(head -n 1 <<< $list)/"
    ;;
  12)
    mpc_add "$1"
    ;;
  *)
    [ -n "$selection" ] && mpc_add "$list"
    ;;
esac
