#!/bin/sh

mpc_add() {
  mpc clear -q
  xargs -I '{}' mpc add -q '{}' <<< "$1"
  mpc play
}

library=$HOME/Music/

cd $library

path=$1

folder="#268bd2"
file="#d33682"

selection=$(\
  find "$path"* -maxdepth 0 -printf "<span foreground='%y'>%f</span>\n" \
  | sed -e "s/<span foreground='d'>/<span foreground='$folder'> /" \
  | sed -e "s/<span foreground='f'>/<span foreground='$file'> /" \
  | sed -e "s/&/&amp;/g" \
  | rofi \
    -dmenu \
    -markup-rows \
    -format p \
    -i \
    -p "library" \
    -multi-select \
    -no-history \
    -kb-custom-1 "Control+o" \
    -kb-custom-2 "Control+i" \
    -kb-custom-3 "Control+t" \
    -kb-accept-alt "Tab" \
    -kb-row-tab ""
)
rofi_signal=$?

selection=$(awk -F' ' '{$1=""} {print substr($0,2)}' <<< $selection)

list=$(sed -e "s#^#$path#" <<< $selection)

case $rofi_signal in
  10)
    target="$(readlink -f "$path/..")/"
    # We do not want to navigate “before” the library in the file tree
    if [ $(wc -c <<< "$target") -ge $(wc -c <<< $library) ]; then
      $0 "$(sed -e "s#$library##" <<< "$target")"
    else
      $0
    fi
    ;;
  11)
    [ -n "$selection" ] && $0 "$(head -n 1 <<< $list)/"
    ;;
  12)
    mpc_add "$1"
    ;;
  *)
    [ -n "$selection" ] && mpc_add "$list"
    ;;
esac
