#!/bin/env sh

notify-send -t 2000 "Starting loading to mpc..."

youtube-dl -g "$1" -f'best' | mpc add \
  && mpc play \
  && notify-send -t 2000 "Finished loading YT to mpc" \
  || notify-send -t 2000 "Failed loading YT to mpc"
