#!/usr/bin/env ruby

# frozen_string_literal: true

require 'cgi'

class SearchEngine

  def initialize(target, fallback: nil, prefixes: [])
    @target = target
    @fallback = fallback
    @prefix = prefixes.map { |s| "#{s} " }.join
  end

  private

  def combine(str)
    if str.strip.empty? && !@fallback.nil?
      @fallback % escape("#{@prefix}#{str}")
    else
      @target % escape("#{@prefix}#{str}")
    end
  end

end

class Man < SearchEngine

  def initialize
    super('man %s')
  end

  def run(str)
    `kitty --class man fish -c '#{combine(str)}'`
  end

  def escape(str)
    str
  end

end

class Browser < SearchEngine

  def initialize(target, fallback: nil, prefixes: [], profile: nil)
    super(target, fallback: fallback, prefixes: prefixes)
    @profile = profile
  end

  def run(str)
    `browser-kiosk #{@profile} '#{combine(str)}'`
  end

  def escape(str)
    CGI.escape(str)
  end

end

class YouTube < Browser

  def initialize
    super(url('results?q=%s'), fallback: url, profile: 'perso')
  end

  def run(str)
    case str
    when 'later' then `browser-kiosk perso '#{url('playlist?list=WL')}'`
    else super(str)
    end
  end

  private

  def url(str=nil)
    "https://www.youtube.com/#{str}"
  end

end

class BrowserRaw < Browser

  def escape(str)
    str
  end

end

defaultengine = Browser.new('https://duckduckgo.com/?ia=web&q=%s')

# rubocop:disable Layout/HashAlignment, Layout/FirstArgumentIndentation, Layout/LineLength
searchengines = {
  'yt'   => YouTube.new,
  'map'  => Browser.new('https://www.google.com/maps/search/%s/', profile: 'perso'),
  'aw'   => Browser.new(
              'https://duckduckgo.com/?ia=web&q=%s',
              prefixes: ['site:https://awesomewm.org/doc'],
              profile: 'perso'
            ),
  'am'   => Browser.new('https://www.amazon.fr/s?k=%s', profile: 'perso'),
  'l'    => Browser.new('http://localhost:%s'),
  'th'   => Browser.new('https://www.thesaurus.com/browse/%s?s=t'),
  'dict' => Browser.new('https://www.larousse.fr/dictionnaires/francais/%s'),
  'trad' => Browser.new('https://translate.google.com/#view=home&op=translate&sl=fr&tl=en&text=%s'),
  'g'    => BrowserRaw.new('https://github.com/%s'),
  'gh'   => Browser.new('https://github.com/search?q=%s'),
  'm'    => Browser.new('https://scryfall.com/search?q=%s', profile: 'perso'),
  'a'    => Browser.new('https://wiki.archlinux.org/index.php/%s'),
  'dt'   => Browser.new('https://www.dndtools.net/spells/?name=%s&_filter=Filter', profile: 'perso'),
  'h'    => Browser.new('https://www.haskell.org/hoogle?hoogle=%s'),
  'r'    => Browser.new('https://reddit.com/r/%s', profile: 'perso'),
  'gem'  => Browser.new('https://rubygems.org/search?query=%s'),
  't'    => Browser.new('https://www.xn--thepratebay-fcb.com/s/?q=%s', profile: 'perso'),
  'tw'   => Browser.new('https://www.twitch.tv/search?term=%s', profile: 'perso'),
  'v'    => Browser.new('https://vimawesome.com/?q=%s'),
  'wp'   => Browser.new('https://wallhaven.cc/search?q=%s&atleast=3440x1440', profile: 'perso'),
  'w'    => Browser.new('https://en.wikipedia.org/wiki/Special:Search?search=%s'),
  'wiki' => Browser.new('https://en.wikipedia.org/wiki/Special:Search?search=%s'),
  'ym'   => Browser.new('https://music.youtube.com/search?q=%s', profile: 'perso'),
  'man'  => Man.new
}
# rubocop:enable Layout/HashAlignment, Layout/FirstArgumentIndentation, Layout/LineLength

query = `rofi -dmenu -p "ﰍ" -theme-str "#content { children: [inputbar]; }"`
words = query.split

if words.any?
  engine = searchengines[words[0]]

  if engine
    words.shift
  elsif words[0].match('http.?://.*')
    engine = Browser.new(words.join)
  end

  (engine || defaultengine).run(words[0..-1].join(' '))
elsif query == "\n"
  `browser-with-context`
end

# vim: textwidth=100
