#!/bin/sh

LAUNCHER='rofi -dmenu -i -p  -l 3'
OPTIONS="fair
tile.right
tile.left
"

option=$(echo "$OPTIONS" | $LAUNCHER | awk '{print $1}')
if [ ${#option} -gt 0 ]; then
awesome-client <<END
  local awful = require('awful')

  awful.layout.set(awful.layout.suit.$option)
  local c = client.focus
  if c then awful.client.setmaster(c) end
END
fi
