#!/usr/bin/env ruby

# frozen_string_literal: true

require 'cgi'

class SearchEngine

  def initialize(target, prefixes: [])
    @target = target
    @prefix = prefixes.map { |s| "#{s} " }.join
  end

  private

  def combine(str)
    @target % escape("#{@prefix}#{str}")
  end

end

class Man < SearchEngine

  def initialize
    super('man %s')
  end

  def run(str)
    `kitty --class man fish -c '#{combine(str)}'`
  end

  def escape(str)
    str
  end

end

class Browser < SearchEngine

  def run(str)
    if str.strip.empty?
      `browser-with-context`
    else
      `browser-kiosk '#{combine(str)}'`
    end
  end

  def escape(str)
    CGI.escape(str)
  end

end

class BrowserRaw < Browser

  def escape(str)
    str
  end

end

defaultengine = Browser.new('https://duckduckgo.com/?ia=web&q=%s')

# rubocop:disable Layout/HashAlignment, Layout/FirstArgumentIndentation, Layout/LineLength
searchengines = {
  'yt'   => Browser.new('https://www.youtube.com/results?q=%s'),
  'map'  => Browser.new('https://www.google.com/maps/search/%s/'),
  'aw'   => Browser.new(
              'https://duckduckgo.com/?ia=web&q=%s',
              prefixes: ['site:https://awesomewm.org/doc']
            ),
  'am'   => Browser.new('https://www.amazon.fr/s?k=%s'),
  'th'   => Browser.new('https://www.thesaurus.com/browse/%s?s=t'),
  'dict' => Browser.new('https://www.larousse.fr/dictionnaires/francais/%s'),
  'trad' => Browser.new('https://translate.google.com/#view=home&op=translate&sl=fr&tl=en&text=%s'),
  'va'   => Browser.new('https://vimawesome.com/?q=%s'),
  'g'    => BrowserRaw.new('https://github.com/%s'),
  'gh'   => Browser.new('https://github.com/search?q=%s'),
  'm'    => Browser.new('https://scryfall.com/search?q=%s'),
  'a'    => Browser.new('https://wiki.archlinux.org/index.php/%s'),
  'dt'   => Browser.new('https://www.dndtools.net/spells/?name=%s&_filter=Filter'),
  'h'    => Browser.new('https://www.haskell.org/hoogle?hoogle=%s'),
  'r'    => Browser.new('https://reddit.com/r/%s'),
  'gem'  => Browser.new('https://rubygems.org/search?query=%s'),
  't'    => Browser.new('https://www.xn--thepratebay-fcb.com/s/?q=%s'),
  'v'    => Browser.new('https://vimawesome.com/?q=%s'),
  'wp'   => Browser.new('https://wallhaven.cc/search?q=%s&atleast=1920x1080'),
  'w'    => Browser.new('https://en.wikipedia.org/wiki/Special:Search?search=%s'),
  'ym'   => Browser.new('https://music.youtube.com/search?q=%s'),
  'man'  => Man.new
}
# rubocop:enable Layout/HashAlignment, Layout/FirstArgumentIndentation, Layout/LineLength

query = `rofi -dmenu -p "" -theme-str "#content { children: [inputbar]; }"`
words = query.split

if words.any?
  engine = searchengines[words[0]]

  if engine
    words.shift
  elsif words[0].match('http.?://.*')
    engine = Browser.new(words.join)
  end

  (engine || defaultengine).run(words[0..-1].join(' '))
elsif query == "\n"
  defaultengine.run('')
end

# vim: textwidth=100
