#!/usr/bin/env sh

cd ~/git/dotfiles/coloriage || exit 1

theme=$(./coloriage list | rofi -theme-str 'listview {columns: 4; lines: 7;} window { width: 30em; }' -dmenu -p 󰸌)
[ -n "$theme" ] && ./coloriage apply "$theme"
