#!/bin/bash

LAUNCHER='rofi -dmenu -lines 4 -i -p ⏼'
OPTIONS=" Lock\n Restart\n Shutdown\n Suspend"

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $2}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]; then
  case $option in
    Lock)
      mpc pause
      betterlockscreen -l blur -t "Password?"
      ;;
    Restart)
      systemctl reboot
      ;;
    Shutdown)
      systemctl poweroff
      ;;
    Suspend)
      mpc pause
      betterlockscreen -s blur -t "Password?"
      ;;
    *)
      ;;
  esac
fi
