#!/bin/sh

LAUNCHER='rofi -dmenu -i -p  '
OPTIONS="fair
tile.right
tile.left"

layout=$(echo "$OPTIONS" | $LAUNCHER | awk '{print "awful.layout.suit."$1}')
if [ ${#layout} -gt 0 ]; then
awesome-client <<-LUA
  local awful = require('awful')

  awful.client.setmaster(client.focus)
  awful.layout.set($layout)
LUA
fi
