#!/bin/bash

LAUNCHER='rofi -dmenu -lines 4 -i -p 拉'
OPTIONS=" Lock\n Restart\n Shutdown\n Suspend"

function lock {
  # i3lock  -f -n -i $HOME/Pictures/lock &
  TMPBG=/tmp/screen.png
  LOCK=$HOME/scripts/lock.png
  RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

  mpc pause

  ffmpeg -y -f x11grab \
    -video_size $RES \
    -i $DISPLAY \
    -i $LOCK \
    -filter_complex "boxblur=12,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" \
    -vframes 1 $TMPBG \
    -loglevel quiet

  i3lock -i $TMPBG -r 242 -o 0.1
  rm $TMPBG
}

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $2}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]; then
  case $option in
    Lock)
      lock
      ;;
    Restart)
      systemctl reboot
      ;;
    Shutdown)
      systemctl poweroff
      ;;
    Suspend)
      lock
      systemctl suspend
      ;;
    *)
      ;;
  esac
fi
