#!/bin/sh

LAUNCHER='rofi -dmenu -i -p  -l 7'
OPTIONS="fair
fair.horizontal
max
tile.right
tile.left
tile.top
tile.bottom"

option=$(echo "$OPTIONS" | $LAUNCHER | awk '{print $1}')
if [ ${#option} -gt 0 ]; then
  echo "
  awful = require('awful')
  awful.layout.set(awful.layout.suit.$option)
  " | awesome-client
fi
