#!/usr/bin/env ruby
# frozen_string_literal: true

mapping = {
  'Bépo' => %w[fr bepo],
  'Qwerty' => ['us', ''],
  'Dvorak' => %w[us dvorak],
  'Colemak' => %w[us colemak],
  'Workman' => %w[us workman],
  'Azerty' => ['fr', '']
}

layout = `setxkbmap -query | grep -e 'layout' | awk -F' ' '{ print $2 }'`.strip
variant = `setxkbmap -query | grep -e 'variant' | awk -F' ' '{ print $2 }'`.strip

current = mapping.invert[[layout, variant]]
id = mapping.keys.find_index(current)

launcher = "rofi -dmenu -i -p  -a #{id}"
options = mapping.keys.join("\n")

selection = `echo "#{options}" | #{launcher} | awk '{print $1}'`.strip

exit 0 if selection == ''

layout, variant = mapping[selection]

`setxkbmap -option ctrl:nocaps -model pc105 -layout "#{layout}" -variant "#{variant}"`

if $? == 0
  `notify-send "Keyboard: success" "Keyboard set to (layout = #{layout}, variant = #{variant})"`
else
  `(notify-send "Keyboard: failure "Could not load (layout = #{layout}, variant = #{variant})"`
end
