#!/bin/bash

LAUNCHER='rofi -dmenu -lines 5 -i -p ⏼'
OPTIONS=" Lock\n Reboot\n Shutdown\n Suspend\n Logout"

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $2}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]; then
  case $option in
    Lock)
      mpc pause
      betterlockscreen -l blur -t "Password?"
      ;;
    Reboot)
      systemctl reboot
      ;;
    Shutdown)
      systemctl poweroff
      ;;
    Suspend)
      mpc pause
      betterlockscreen -s blur -t "Password?"
      ;;
    Logout)
      echo "awesome.quit()" | awesome-client
      ;;
    *)
      ;;
  esac
fi
