#!/bin/bash

layout=`setxkbmap -query | grep layout | awk -F ' ' '{print $2}'`
variant=`setxkbmap -query | grep variant | awk -F ' ' '{print $2}'`
current="$layout:$variant"

case $current in
  "fr:bepo")
    layout="us"
    variant=""
    ;;
  *)
    layout="fr"
    variant="bepo"
    ;;
esac

if [[ $(setxkbmap -option ctrl:nocaps -model pc105 -layout "$layout" -variant "$variant") ]]; then
  notify-send Failure "Could not load (layout = $layout, variant = $variant)"
else
  notify-send Success "Keyboard set to (layout = $layout, variant = $variant)"
fi

xmodmap ~/.Xmodmap
