#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

function display {
  label="$1"
  out="$2"

  echo

  if [ -z "$out" ]; then
    echo "   $label: ø"
  else
    echo "   $label:"
    echo "$out"
  fi
}

display Active "$(task rc.verbose:headers active 2> /dev/null)"

if [ "$CONTEXT" == "work" ]; then
  display Hiring "$(task rc.verbose:headers hiring 2> /dev/null)"
fi

display Next "$(task rc.verbose:headers 2> /dev/null)"
display Inbox "$(task rc.verbose:headers in 2> /dev/null)"

echo
echo "   Blocking/Blocked → `task rc.verbose:none +BLOCKING count`/`task rc.verbose:none +BLOCKED count`"

if [ $(task _get tw.syncneeded) == 1 ]; then
  echo -e "\n   \e[33mSync needed\e[39m"
fi
