#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

function display {
  label="$1"
  out="$2"

  echo

  if [ -z "$out" ]; then
    echo "   $label: ø"
  else
    echo "   $label:"
    echo "$out"
  fi
}

function maybeDisplay {
  label="$1"
  out="$2"

  if [ -n "$out" ]; then
    echo
    echo "   $label:"
    echo "$out"
  fi
}

priorityfile="$HOME/.priorities.$CONTEXT"
if [ -f "$priorityfile" ]; then
  echo -e "\n   \e[31mHot topics\n"
  sed -e '/^./ s/^/   => /' "$priorityfile"
  echo -ne "\e[39m"
fi

display Active "$(task rc.verbose:headers active 2> /dev/null)"

display Next "$(task rc.verbose:headers 2> /dev/null)"
display Inbox "$(task rc.verbose:headers in 2> /dev/null)"
maybeDisplay "Continuous Improvement" "$(task rc.verbose:headers improvements 2> /dev/null)"
maybeDisplay Shopping "$(task rc.verbose:headers shopping 2> /dev/null)"
maybeDisplay Recents "$(task rc.verbose:headers recent 2> /dev/null)"

echo
echo "   Blocking/Blocked → `task rc.verbose:none +BLOCKING count`/`task rc.verbose:none +BLOCKED count`"

if [ $(task _get tw.syncneeded) == 1 ]; then
  echo -e "\n   \e[33mSync needed\e[39m"
fi
