#!/usr/bin/env sh

function search {
  ag 'TODO|XXX' \
    --ignore=app/assets/frontend/src/common_assets/javascripts/limitless
}

function gitsearch {
  git diff $1 -G 'TODO|XXX' --name-only --diff-filter=d
}

function prefix {
  awk '{print "→  " $0}'
}

case $1 in
  .)  todo=$(gitsearch HEAD | prefix);;
  ..) todo=$(gitsearch develop.. | prefix);;
  *)  todo=$(search | prefix);;
esac

ponysay -W i "$todo"
