#!/usr/bin/env sh

function search {
  path=$1
  ag 'TODO|XXX' $path\
    --ignore=app/assets/frontend/src/common_assets/javascripts/limitless
}

function gitdiff {
  git diff $1 --name-only --diff-filter=d
}

function prefix {
  awk '{print "→  " $0}'
}

case $1 in
  .)  todo=$(ag 'TODO|XXX' $(git diff HEAD --name-only --diff-filter=d) --ignore=app/assets/frontend/src/common_assets/javascripts/limitless | awk '{print "→ " $0}');;
  ..) todo=$(ag 'TODO|XXX' $(git diff master.. --name-only --diff-filter=d) --ignore=app/assets/frontend/src/common_assets/javascripts/limitless | awk '{print "→ " $0}');;
  *)  todo=$(search | prefix)
esac

ponysay -W i "$todo"
