#!/bin/sh

if [ "$1" = 'restart' ]; then pkill -USR2 -f '^puma'; fi

if wmctrl -x -l | grep rails | grep -q kitty.kitty; then exit 0; fi

kitty --session work &
sleep 0.5
browser-kiosk http://localhost:3000 &

awesome-client <<-LUA
  local awful = require('awful')
  awful.client.setmaster(client.focus)
  awful.layout.set(awful.layout.suit.tile.left)
LUA
