#!/bin/sh

pkill -USR2 -f '^puma'

if [ $? -eq 0 ]; then exit 0; fi

kitty --session work &
sleep 0.5
browser-kiosk http://localhost:3000 &

awesome-client <<-LUA
  local awful = require('awful')
  awful.client.setmaster(client.focus)
  awful.layout.set(awful.layout.suit.tile.left)
LUA
