#!/bin/sh

mkdir -p /tmp/ytdl
cd /tmp/ytdl || exit

url=$(xsel --clipboard -o)
cmd="yt-dlp --add-chapters --sponsorblock-mark all"

notify-send "Download started" "Your download will be available in $(pwd)"

$cmd "$url"
if [ $? != 0 ]; then
  notify-send "Error" "Could not download in playlist mode, retrying in single mode"
  $cmd --no-playlist "$url"
fi

if [ $? = 0 ]; then
  notify-send "Finished downloading" "You can find it in $(pwd)"
else
  notify-send "Something went wrong with your download"
fi
