return {
  'nvimdev/dashboard-nvim',
  event = 'VimEnter',
  opts = {
    theme = 'doom',
    config = {
      disable_move = true,
      header = {
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        [[                                                                       ]],
        [[                                                                     ]],
        [[       ████ ██████           █████      ██                     ]],
        [[      ███████████             █████                             ]],
        [[      █████████ ███████████████████ ███   ███████████   ]],
        [[     █████████  ███    █████████████ █████ ██████████████   ]],
        [[    █████████ ██████████ █████████ █████ █████ ████ █████   ]],
        [[  ███████████ ███    ███ █████████ █████ █████ ████ █████  ]],
        [[ ██████  █████████████████████ ████ █████ █████ ████ ██████ ]],
        [[                                                                       ]],
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
      },
      center = {
        {
          icon = '󰏓 ',
          icon_hl = 'Comment',
          desc = 'Lazy',
          desc_hl = 'Nontext',
          key = 'l',
          key_hl = 'Comment',
          key_format = ' %s',
          action = 'Lazy',
        },
        {
          icon = ' ',
          icon_hl = 'Comment',
          desc = 'Mason',
          desc_hl = 'Nontext',
          key = 'm',
          key_hl = 'Comment',
          key_format = ' %s',
          action = 'Mason',
        },
        {
          icon = '⏻ ',
          icon_hl = 'Comment',
          desc = 'Quit',
          desc_hl = 'Nontext',
          key = 'q',
          key_hl = 'Comment',
          key_format = ' %s',
          action = 'quit',
        },
      },
    },
  },
}
