return {
  'tpope/vim-fugitive',
  dependencies = {
    'junegunn/gv.vim',
    'tpope/vim-rhubarb',
  },
  cmd = { 'Git', 'Gvdiff', 'GV', 'Gcd' },
  keys = {
    { '<leader>gW', '<cmd>Git add .<cr>', desc = 'Git add .', silent = true },
    { '<leader>ga', '<cmd>Git commit --quiet --amend --no-edit<cr>', desc = 'Git commit --amend --no-edit', silent = true },
    { '<leader>gA', '<cmd>Git commit --quiet --amend<cr>', desc = 'Git commit --amend', silent = true },
    { '<leader>gc', '<cmd>Git commit --quiet<cr>', desc = 'Git commit', silent = true },
    { '<leader>gd', '<cmd>leftabove Gvdiff<cr>', desc = 'Git diff', silent = true },
    { '<leader>gD', '<cmd>leftabove Gvdiff master<cr>', desc = 'Git diff master..', silent = true },
    { '<leader>ed', '<cmd>tab Git diff --staged<cr>', desc = 'Git diff --staged', silent = true },
    { '<leader>gr', '<cmd>Git checkout %<cr>', desc = 'Git checkout %', silent = true },
    { '<leader>gs', '<cmd>Git<cr>', desc = 'Git', silent = true },
    { '<leader>gl', '<cmd>GV<cr>', desc = 'GV', silent = true },
    { '<leader>gp', '<cmd>Git push --force-with-lease<cr>', desc = 'Git push --force-with-lease', silent = true },
    { '<leader>gu', '<cmd>Git pull --rebase<cr>', desc = 'Git pull --rebase', silent = true },
    { '<leader>cc', '<cmd>Gcd<cr>', desc = 'Git CWD' },
    {
      '<leader>gy',
      ':GBrowse!<cr>',
      mode = { 'v', 'n' },
      desc = 'Git(Hub) yank file URL',
      silent = true,
    },
    {
      '<leader>gl',
      ":'<,'>GV<cr>",
      mode = 'x',
      desc = 'GV (visual mode)',
      silent = true,
    },
  },
}
