return {
  'tpope/vim-fugitive',
  dependencies = {
    'junegunn/gv.vim',
    'tpope/vim-rhubarb',
  },
  cmd = { 'Git', 'Gvdiff', 'GV' },
  keys = {
    { '<leader>gW', ':Git add .<cr>',                            desc = 'Git add .',                    silent = true },
    { '<leader>ga', ':Git commit --quiet --amend --no-edit<cr>', desc = 'Git commit --amend --no-edit', silent = true },
    { '<leader>gA', ':Git commit --quiet --amend<cr>',           desc = 'Git commit --amend',           silent = true },
    { '<leader>gc', ':Git commit --quiet<cr>',                   desc = 'Git commit',                   silent = true },
    { '<leader>gd', ':leftabove Gvdiff<cr>',                     desc = 'Git diff',                     silent = true },
    { '<leader>gD', ':leftabove Gvdiff master<cr>',              desc = 'Git diff master..',            silent = true },
    { '<leader>ed', ':tab Git diff --staged<cr>',                desc = 'Git diff --staged',            silent = true },
    { '<leader>gr', ':Git checkout %<cr>',                       desc = 'Git checkout %',               silent = true },
    { '<leader>gs', ':Git<cr>',                                  desc = 'Git',                          silent = true },
    { '<leader>gS', ':GV<cr>',                                   desc = 'GV',                           silent = true },
    { '<leader>gp', ':Git push --force-with-lease<cr>',          desc = 'Git push --force-with-lease',  silent = true },
    { '<leader>gu', ':Git pull --rebase<cr>',                    desc = 'Git pull --rebase',            silent = true },
    {
      '<leader>gy',
      ':GBrowse!<cr>',
      mode = { 'v', 'n' },
      desc = 'Git(Hub) yank file URL',
      silent = true,
    },
    {
      '<leader>gS',
      ":'<,'>GV<cr>",
      mode = 'x',
      desc = 'GV (visual mode)',
      silent = true,
    },
  },
}
