return {
  'nvim-tree/nvim-web-devicons',
  opts = {
    default = true,
    override = {
      help = { icon = '' },
      man = { icon = '' },
      qf = { icon = '󰁨' },
      query = { icon = '󰙅' }, -- treesitter tree view

      harpoon = { icon = '🪝' },
      mason = { icon = '󰣪' },
      lazy = { icon = '󰘧' },
      TelescopePrompt = { icon = '', name = 'telescope' },
      oil = { icon = '' },

      norg = { icon = '󱗖' },

      xf86conf = { icon = '' },
      xdefaults = { icon = '' },
      desktop = { icon = '󰍹' },

      make = { icon = '󱁻' },
      vim = { icon = '' },
      json = { icon = '' },
      html = { icon = '' },
      eruby = { icon = '' },
      ['eruby.html'] = { icon = '' },
      css = { icon = '' },
      go = { icon = '' },
      gomod = { icon = '' },
      ocaml = { icon = '' },
      dune = { icon = '' },
      markdown = { icon = '' },
      lua = { icon = '' },
      toml = { icon = '' },
      ruby = { icon = '' },
      python = { icon = '' },
      cpp = { icon = '' },
      c = { icon = '' },
      gitcommit = { icon = '' },
      ['.gitignore'] = { icon = '' },
      ['.gitconfig'] = { icon = '' },
      ['gitconfig'] = { icon = '' },
      ['.gitattributes'] = { icon = '' },
      fugitive = { icon = '' },
      GV = { icon = '' },
      haskell = { icon = '󰲒' },
      rust = { icon = '' },
      java = { icon = '' },
      jar = { icon = '' },
      javascript = { icon = '' },
      jsx = { icon = '󰜈' },
      javascriptreact = { icon = '󰜈' },
      ['javascript.jsx'] = { icon = '󰜈' },
      ['test.js'] = { icon = '' },
      ['test.jsx'] = { icon = '󰜈' },
      ['spec.js'] = { icon = '' },
      ['spec.jsx'] = { icon = '󰜈' },
      typescript = { icon = '' },
      typescriptreact = { icon = '' },
      ['test.ts'] = { icon = '' },
      ['test.tsx'] = { icon = '󰜈' },
      ['spec.ts'] = { icon = '' },
      ['spec.tsx'] = { icon = '󰜈' },
      ['favicon.ico'] = { icon = '' },
      lock = { icon = '' },
      log = { icon = '' },
    },
    override_by_extension = {
      mod = { icon = '' },
      rb = { icon = '' },
      ru = { icon = '' },
      erb = { icon = '' },
      png = { icon = '󰸭' },
      jpg = { icon = '󰈥' },
      svg = { icon = '' },
      js = { icon = '' },
      md = { icon = '' },
      ml = { icon = '' },
      mli = { icon = '' },
      exe = { icon = '' },
      log = { icon = '' },
    },
    override_by_filename = {
      ['.keep'] = { icon = '' },

      ['dune-project'] = { icon = '' },
      makefile = { icon = '󱁻' },

      ['robots.txt'] = { icon = '󱚝' },
      gemfile = { icon = '' },
      rake = { icon = '' },
      rakefile = { icon = '' },
      ['config.ru'] = { icon = '' },
      ['routes.rb'] = { icon = '' },
      ['seeds.rb'] = { icon = '' },
      ['database.yml'] = { icon = '󱙋' },
      ['.ruby-version'] = { icon = '󰎠' },

      ['package.json'] = { icon = '' },

      dockerfile = { icon = '' },
      ['docker-compose.yml'] = { icon = '' },
      ['.dockerignore'] = { icon = '' },

      license = { icon = '󰿃' },
    }
  },
  config = function(_, opts)
    local plug = require('nvim-web-devicons')
    plug.setup(opts)
    plug.set_default_icon('')
  end
}
