#!/bin/sh

config="$HOME/.browser-config"
[ -f "$config" ] && . "$config"

launch_browser() {
  chromium --app="$1" --profile-directory="$profile"
}

launch_mpv() {
  mpv "$1"
}

case "$1" in
  # some videos can't be launched in mpv, such as subscribers only feeds
  *youtu.be/*) launch_mpv "$1" || launch_browser "$1";;
  *www.youtube.com/watch\?*) launch_mpv "$1" || launch_browser "$1";;
  *www.youtube.com/shorts/*) launch_mpv "$1" || launch_browser "$1";;
  *changelog.com/podcast/feed) launch_browser "$1";;
  *changelog.com/*/*) launch_mpv "$1" || launch_browser "$1";;
  *) launch_browser "$1";;
esac
