#!/bin/sh

launch_browser() {
  config="$HOME/.browser-config"
  [ -f "$config" ] && . "$config"
  chromium --app="$1" --profile-directory="$profile"
}

launch_mpv() {
  mpv "$1"
}

case "$1" in
  # some videos can't be launched in mpv, such as subscribers only feeds
  *www.youtube.com/watch?*) launch_mpv "$1" || launch_browser "$1";;
  *) launch_browser "$1";;
esac
