#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

context=${CONTEXT:-"home"}

if [ "$context" == "home" ]; then
  notion "tlarrieu/40a05b9746904e04911db5346ee92a5d"
else
  notion "tlarrieu/2fd3c97e4ef64dcfb391ed2b348ef9f0"
fi
