#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

context=${CONTEXT:-"home"}

# if [ "$context" == "home" ]; then
#   view="7aafff1636c448c181a98f5c834487a9"
# else
#   view="028e8f58a4d443a1a75141ec9ab7d489"
# fi

# notion "tlarrieu/098cc238c6324106959eecc4324be158?v=$view"

if [ "$context" == "home" ]; then
  view="YVPmxJmRi7tNFeDgbfk6WJ23#z=KJbXK8j9UNCTQXMyEz3Ra8yC"
else
  view="YVPmxJmRi7tNFeDgbfk6WJ23#z=k3CGqnmVHuBfSUDli3G6wILE"
fi

dynalist "$view"
