#!/bin/sh

envfile="$HOME/.chromium.env"
[ -f "$envfile" ] && source "$envfile"

echo "$1" | grep jobteaser > /dev/null

if [[ $? -eq 0 ]]; then
  profile=$CHROMIUM_WORK
else
  profile=$CHROMIUM_PERSONAL
fi

profile=${profile:-"Default"}

if [[ "$1" == "https"* ]]; then
  chromium \
    --app="$1" \
    --profile-directory="$profile"
else
  chromium \
    --app="https://www.notion.so/$1" \
    --profile-directory="$profile"
fi

