#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

context=${CONTEXT:-"home"}

if [ "$context" == "home" ]; then
  dynalist "T4LXOQurhn_O8rXnORg0xMb4#z=E1Dj2K81QBbkXdI8fTADFJhw"
else
  if [ $(date +%H) -le 12 ]; then
    dynalist "T4LXOQurhn_O8rXnORg0xMb4#z=D_i5Zuv27YUJZaFn07erCyDq"
  else
    dynalist "T4LXOQurhn_O8rXnORg0xMb4#z=MHio82HOONH1FH1Ytm84Uoms"
  fi
fi
