#!/bin/sh

envfile="$HOME/.context.env"
[ -f "$envfile" ] && source "$envfile"

context=${CONTEXT:-"home"}

if [ "$context" == "home" ]; then
  task proj:routine +@home routine
else
  if [ $(date +%H) -le 12 ]; then
    task proj:routine.morning +@work routine
  else
    task proj:routine.afternoon +@work routine
  fi
fi
