#!/bin/sh

envfile="$HOME/.chromium.env"
[ -f "$envfile" ] && source "$envfile"

profile=${CHROMIUM_WORK:-"Default"}

chromium \
  --app="https://jobteaser.slack.com" \
  --profile-directory="$profile"
