return function(palette)
  vim.api.nvim_set_hl(0, 'Directory', { fg = palette.blue.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'OilLink', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'OilFileHidden', { fg = palette.fg.dimmer, italic = true })
  vim.api.nvim_set_hl(0, 'OilLinkHidden', { fg = palette.yellow.base, italic = true })
  vim.api.nvim_set_hl(0, 'OilLinkTarget', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'OilLinkTargetHidden', { fg = palette.fg.dimmer, italic = true })
  vim.api.nvim_set_hl(0, 'OilOrphanLinkTargetHidden', { fg = palette.red.base, italic = true })
  vim.api.nvim_set_hl(0, 'OilDir', { fg = palette.blue.base })
  vim.api.nvim_set_hl(0, 'OilDirHidden', { fg = palette.blue.base, italic = true })
  vim.api.nvim_set_hl(0, 'OilDirIcon', { link = 'OilDir' })
  vim.api.nvim_set_hl(0, 'OilCreate', { link = 'Added' })
  vim.api.nvim_set_hl(0, 'OilDelete', { link = 'Removed' })
  vim.api.nvim_set_hl(0, 'OilTrash', { link = 'OilDelete' })
  vim.api.nvim_set_hl(0, 'OilPurge', { link = 'OilDelete' })
  vim.api.nvim_set_hl(0, 'OilChange', { link = 'Changed' })
  vim.api.nvim_set_hl(0, 'OilMove', { link = 'OilChange' })

  vim.api.nvim_set_hl(0, 'HarpoonLine', { link = 'QuickFixLine' })

  vim.api.nvim_set_hl(0, 'DropBarIconUISeparator', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'DropBarIconUISeparatorNC', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'DropBarIconUIIndicator', { link = 'DropBarIconUISeparator' })
  vim.api.nvim_set_hl(0, 'DropBarCurrentContext', { bg = palette.sel.base })
  vim.api.nvim_set_hl(0, 'DropBarCurrentIcon', { link = 'DropBarCurrentContext' })
  vim.api.nvim_set_hl(0, 'DropBarCurrentName', { link = 'DropBarCurrentContext' })
  vim.api.nvim_set_hl(0, 'DropBarCurrentHover', { link = 'DropBarCurrentContext' })
  vim.api.nvim_set_hl(0, 'DropBarKindDefault', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, 'DropBarKindFile', { fg = palette.fg.dim, bold = true })
  vim.api.nvim_set_hl(0, 'DropBarIconKindTerminal', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindDefault', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, 'DropBarIconKindFolder', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindObject', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindEnum', { link = 'DropBarIconKindType' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindCall', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindNull', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindConstant', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindStatement', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindFunction', { link = 'DropBarIconKindDefault' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMethod', { link = 'DropBarIconKindFunction' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH1', { link = '@markup.heading.1' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH2', { link = '@markup.heading.2' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH3', { link = '@markup.heading.3' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH4', { link = '@markup.heading.4' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH5', { link = '@markup.heading.5' })
  vim.api.nvim_set_hl(0, 'DropBarIconKindMarkdownH6', { link = '@markup.heading.6' })
  vim.api.nvim_set_hl(0, 'DropBarMenuHoverSymbol', { fg = palette.fg.dim, bold = true })
  vim.api.nvim_set_hl(0, 'DropBarMenuCurrentContext', { bg = palette.sel.base })
  vim.api.nvim_set_hl(0, 'DropBarMenuHoverIcon', { bg = palette.sel.base })
  vim.api.nvim_set_hl(0, 'DropBarMenuHoverEntry', { link = 'DropBarMenuHoverIcon' })
  vim.api.nvim_set_hl(0, 'DropBarModified', { fg = palette.pink.base, bold = true })

  vim.api.nvim_set_hl(0, 'TelescopeNormal', { fg = palette.fg.dim, bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', { fg = palette.fg.base, bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'TelescopeBorder', { link = 'FloatBorder' })
  vim.api.nvim_set_hl(0, 'TelescopeTitle', { fg = palette.fg.dim, bg = 'none', bold = true })
  vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { link = 'FloatBorder' })
  vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { fg = palette.fg.dim, bold = true })
  vim.api.nvim_set_hl(0, 'TelescopePromptNormal', { fg = palette.bg.base, bg = palette.fg.base })
  vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { link = 'TelescopePromptTitle' })
  vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { fg = palette.fg.base, bg = palette.fg.base })
  vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = palette.bg.base, bg = palette.fg.base })
  vim.api.nvim_set_hl(0, 'TelescopePromptCounter', { link = 'TelescopePromptPrefix' })
  vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = palette.sel.base })
  vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { link = 'TelescopeSelection' })
  vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = palette.accent.base })
  vim.api.nvim_set_hl(0, 'TelescopeMultiSelection', { bg = palette.sel.base, bold = true })
  vim.api.nvim_set_hl(0, 'TelescopeMultiIcon', { link = 'TelescopeMultiSelection' })
  vim.api.nvim_set_hl(0, 'TelescopeResultsComment', { fg = palette.fg.dimmer, italic = true })
  vim.api.nvim_set_hl(0, 'TelescopeResultsDiffAdd', { link = 'Added' })
  vim.api.nvim_set_hl(0, 'TelescopeResultsDiffDelete', { link = 'Removed' })
  vim.api.nvim_set_hl(0, 'TelescopeResultsDiffChange', { link = 'Changed' })
  vim.api.nvim_set_hl(0, 'TelescopeResultsIdentifier', { fg = palette.magenta.base, italic = true })

  vim.api.nvim_set_hl(0, 'MasonHeader', { fg = palette.green.base, bg = palette.green.dim })
  vim.api.nvim_set_hl(0, 'MasonHighlight', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MasonHighlightBlock', { fg = palette.bg.base, bg = palette.green.bright })
  vim.api.nvim_set_hl(0, 'MasonHighlightBlockBold', { link = 'MasonHeader' })
  vim.api.nvim_set_hl(0, 'MasonMutedBlock', { fg = palette.fg.dimmer, bg = palette.bg.base })

  vim.api.nvim_set_hl(0, 'LualineAdded', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, 'LualineRemoved', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, 'LualineModified', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'LualineTablineActive', { fg = palette.bg.base, bg = palette.blue.base })
  vim.api.nvim_set_hl(0, 'LualineTablineActiveAlt', {
    fg = palette.fg.base,
    bg = palette.bg.base,
    bold = true,
    underline = true,
  })
  vim.api.nvim_set_hl(0, 'LualineTablineInactive', { fg = palette.fg.base, bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'LualineExecutable', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'LualineSuccess', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'LualineNotice', { fg = palette.fg.dimmer, bg = 'none' })
  vim.api.nvim_set_hl(0, 'LualineError', { fg = palette.red.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'LualineWarning', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'LualineMacroRecording', { fg = palette.red.base, bg = 'none' })

  vim.api.nvim_set_hl(0, 'FidgetTitle', { link = 'Title' })
  vim.api.nvim_set_hl(0, 'FidgetTask', { link = 'LineNr' })
  vim.api.nvim_set_hl(0, 'FidgetGroup', { fg = palette.accent.base, bold = true })
  vim.api.nvim_set_hl(0, 'FidgetNormal', { fg = palette.fg.base, bg = palette.bg.dimmer })
  vim.api.nvim_set_hl(0, 'FidgetBorder', { link = 'FidgetNormal' })
  vim.api.nvim_set_hl(0, 'FidgetProgress', { fg = palette.orange.base })
  vim.api.nvim_set_hl(0, 'FidgetDone', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, 'FidgetGroupSeparator', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { fg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { fg = palette.blue.base })
  vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { fg = palette.blue.base })
  vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { fg = palette.cyan.base })
  vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { link = 'NotifyERRORTitle' })
  vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { link = 'NotifyWARNTitle' })
  vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { link = 'NotifyINFOTitle' })
  vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { link = 'NotifyDEBUGTitle' })
  vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { link = 'NotifyTRACETitle' })
  vim.api.nvim_set_hl(0, 'NotifyBackground', { link = 'NormalFloat' })

  vim.api.nvim_set_hl(0, 'MarkSignHL', { fg = palette.accent.base, bg = palette.accent.dim })
  vim.api.nvim_set_hl(0, 'MarkSignNumHL', { fg = palette.fg.dim, bg = palette.accent.dim })
  vim.api.nvim_set_hl(0, 'MarkVirtTextHL', { fg = palette.accent.base, bg = palette.accent.dim })

  vim.api.nvim_set_hl(0, 'MarkviewCode', { fg = 'none', bg = palette.bg.dimmer })
  vim.api.nvim_set_hl(0, 'MarkviewCodeLabel', { fg = palette.bg.dimmer, bg = palette.yellow.base, bold = true })
  vim.api.nvim_set_hl(0, 'MarkviewInlineCode', { fg = 'none', bg = palette.bg.dimmer })
  vim.api.nvim_set_hl(0, 'MarkviewHyperlink', { fg = palette.magenta.base, bg = 'none', italic = true })
  vim.api.nvim_set_hl(0, 'MarkviewImage', { fg = palette.blue.base, bg = 'none', italic = true })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteDefault', { fg = palette.fg.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteError', { fg = palette.red.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteNote', { fg = palette.blue.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteOk', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteSpecial', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteWarn', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewFatHeading1', { fg = palette.pink.base, bg = palette.pink.dim })
  vim.api.nvim_set_hl(0, 'MarkviewFatHeading2', { fg = palette.green.base, bg = palette.green.dim })
  vim.api.nvim_set_hl(0, 'MarkviewHeading1', { fg = palette.pink.base, bg = palette.pink.dim })
  vim.api.nvim_set_hl(0, 'MarkviewHeading2', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewHeading3', { fg = palette.blue.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewHeading4', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewHeading5', { fg = palette.cyan.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewHeading6', { fg = palette.magenta.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewListItemMinus', { fg = palette.pink.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewListItemStar', { fg = palette.green.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewListItemPlus', { fg = palette.cyan.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette0', { fg = 'none', bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'MarkviewPalette1', { fg = palette.bg.base, bg = palette.pink.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette2', { fg = palette.bg.base, bg = palette.green.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette3', { fg = palette.bg.base, bg = palette.blue.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette4', { fg = palette.bg.base, bg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette5', { fg = palette.bg.base, bg = palette.cyan.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette6', { fg = palette.bg.base, bg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'MarkviewPalette1Sign', { fg = palette.pink.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette2Sign', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette3Sign', { fg = palette.blue.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette4Sign', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette5Sign', { fg = palette.cyan.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewPalette6Sign', { fg = palette.magenta.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewCheckboxChecked', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewCheckboxUnchecked', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewCheckboxStriked', { fg = palette.fg.dim, bg = 'none', strikethrough = true })
  vim.api.nvim_set_hl(0, 'MarkviewGradient0', { fg = '#cccdc1', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient1', { fg = '#c4c8bd', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient2', { fg = '#bdc3b9', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient3', { fg = '#b6bfb5', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient4', { fg = '#afbab1', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient5', { fg = '#a9b5ae', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient6', { fg = '#a2b0aa', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient7', { fg = '#9daaa7', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient8', { fg = '#97a5a3', bg = 'none' })
  vim.api.nvim_set_hl(0, 'MarkviewGradient9', { fg = '#92a0a0', bg = 'none' })

  vim.api.nvim_set_hl(0, 'gitHash', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'gitIdentity', { fg = palette.accent.base })
  vim.api.nvim_set_hl(0, 'gitEmail', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, 'gitEmailDelimiter', { link = 'gitEmail' })
  vim.api.nvim_set_hl(0, 'gitDate', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'gitDiff', { fg = palette.fg.dim })

  vim.api.nvim_set_hl(0, 'fugitiveHeader', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveHunk', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveHash', { link = 'gitHash' })
  vim.api.nvim_set_hl(0, 'fugitiveSymbolicRef', { link = '@git.branch' })
  vim.api.nvim_set_hl(0, 'fugitiveHelpTag', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveHeading', { fg = palette.fg.dim, italic = true })
  vim.api.nvim_set_hl(0, 'fugitiveUnstagedHeading', { fg = palette.yellow.base, bg = palette.yellow.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveUnstagedModifier', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'fugitiveStagedHeading', { fg = palette.green.base, bg = palette.green.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveStagedModifier', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, 'fugitiveUntrackedHeading', { fg = palette.red.base, bg = palette.red.dimmer })
  vim.api.nvim_set_hl(0, 'fugitiveUntrackedModifier', { fg = palette.red.base })

  vim.api.nvim_set_hl(0, 'flogBranch1', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'flogBranch2', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch3', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch4', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch5', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch6', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch7', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogBranch8', { link = 'flogBranch1' })
  vim.api.nvim_set_hl(0, 'flogDate', { link = 'gitDate' })
  vim.api.nvim_set_hl(0, 'flogHash', { link = 'gitHash' })
  vim.api.nvim_set_hl(0, 'flogRef', { fg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'flogRefHead', { fg = palette.accent.base })
  vim.api.nvim_set_hl(0, 'flogRefHeadBranch', { link = 'flogRefHead' })
  vim.api.nvim_set_hl(0, 'flogRefTag', { fg = palette.magenta.base })

  vim.api.nvim_set_hl(0, 'CodeDiffMoveTo', { fg = palette.fg.dim, bg = palette.bg.dim, italic = true })
  vim.api.nvim_set_hl(0, 'CodeDiffMoveFrom', { link = 'CodeDiffMoveTo' })
  vim.api.nvim_set_hl(0, 'CodeDiffLineMove', { bg = palette.bg.dim, italic = true, nocombine = true })

  vim.api.nvim_set_hl(0, '@comment.gitcommit', { fg = palette.fg.dimmer, bg = 'none' })
  vim.api.nvim_set_hl(0, '@markup.heading.gitcommit', { fg = palette.fg.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@text.reference.gitcommit', { link = '@markup.link.gitcommit' })
  vim.api.nvim_set_hl(0, '@text.uri.gitcommit', { fg = palette.fg.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@string.special.path.gitcommit', { fg = palette.magenta.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@keyword.gitcommit', { fg = palette.orange.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@markup.heading.git_config', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, '@string.special.path.git_config', { link = '@string' })
  vim.api.nvim_set_hl(0, '@comment.git', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, '@git.subject', { fg = palette.fg.base, bold = true })
  vim.api.nvim_set_hl(0, '@git.message', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, '@git.branch', { fg = palette.magenta.base, bg = palette.magenta.dimmer })
  vim.api.nvim_set_hl(0, '@git.title.committed', { fg = palette.green.base, bg = 'none', bold = true })
  vim.api.nvim_set_hl(0, '@git.title.not_committed', { fg = palette.yellow.base, bg = 'none', bold = true })
  vim.api.nvim_set_hl(0, '@git.title.untracked', { fg = palette.red.base, bg = 'none', bold = true })
  vim.api.nvim_set_hl(0, '@git.change.deleted', { fg = palette.fg.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.modified', { fg = palette.fg.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.new', { fg = palette.fg.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.renamed', { fg = palette.fg.dim, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.deleted.filepath', { fg = palette.red.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.modified.filepath', { fg = palette.yellow.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.new.filepath', { fg = palette.green.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@git.change.renamed.filepath', { fg = palette.orange.base, bg = 'none' })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.pick', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.reword', { fg = palette.blue.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.edit', { fg = palette.blue.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.squash', { fg = palette.orange.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.fixup', { fg = palette.orange.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.exec', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.break', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.drop', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.label', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.reset', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.merge', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.update-ref', { fg = palette.pink.base })
  vim.api.nvim_set_hl(0, '@keyword.git_rebase.invalid', { fg = palette.red.base, bg = palette.red.dim, undercurl = true })
  vim.api.nvim_set_hl(0, '@constant.git_rebase', { fg = palette.magenta.base, italic = true })
  vim.api.nvim_set_hl(0, '@none.git_rebase', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, '@string.special.path.gitignore', { link = '@normal' })
  vim.api.nvim_set_hl(0, '@punctuation.delimiter.gitignore', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, '@character.special.gitignore', { link = '@normal' })

  vim.api.nvim_set_hl(0, 'DiffAdd', { bg = palette.green.dim })
  vim.api.nvim_set_hl(0, 'DiffDelete', { fg = palette.red.dim, bg = palette.red.dim })
  vim.api.nvim_set_hl(0, 'DiffChange', { bg = palette.yellow.dim })
  vim.api.nvim_set_hl(0, 'DiffMove', { bg = palette.bg.dimmer }) -- codediff related
  vim.api.nvim_set_hl(0, 'DiffText', { bg = palette.blue.dim })
  vim.api.nvim_set_hl(0, 'diffAdded', { link = 'DiffAdd' })
  vim.api.nvim_set_hl(0, 'diffRemoved', { bg = palette.red.dim })
  vim.api.nvim_set_hl(0, 'diffChanged', { link = 'DiffChange' })
  vim.api.nvim_set_hl(0, 'diffFile', { fg = palette.bg.base })
  vim.api.nvim_set_hl(0, 'diffIndexLine', { fg = palette.blue.base, italic = true })
  vim.api.nvim_set_hl(0, 'diffOldFile', { fg = palette.yellow.base, italic = true })
  vim.api.nvim_set_hl(0, 'diffNewFile', { fg = palette.green.base, italic = true })
  vim.api.nvim_set_hl(0, 'diffLine', { fg = palette.blue.base, bg = palette.blue.dim, bold = true })
  vim.api.nvim_set_hl(0, 'diffSubname', { fg = palette.fg.dimmer })

  vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = palette.green.base, bg = palette.green.dim })
  vim.api.nvim_set_hl(0, 'GitSignsAddNr', { link = 'GitSignsAdd' })
  vim.api.nvim_set_hl(0, 'GitSignsAddLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsAddInline', { fg = 'none', bg = palette.green.base })
  vim.api.nvim_set_hl(0, 'GitSignsAddInlineNr', { link = 'GitSignsAddInline' })
  vim.api.nvim_set_hl(0, 'GitSignsAddInlineLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = palette.red.base, bg = palette.red.dim })
  vim.api.nvim_set_hl(0, 'GitSignsDeleteNr', { link = 'GitSignsDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsTopDelete', { link = 'GitSignsDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsTopDeleteNr', { link = 'GitSignsTopDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsDeleteInline', { fg = 'none', bg = palette.red.base })
  vim.api.nvim_set_hl(0, 'GitSignsDeleteInlineNr', { link = 'GitSignsDeleteInline' })
  vim.api.nvim_set_hl(0, 'GitSignsDeleteInlineLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = palette.yellow.base, bg = palette.yellow.dim })
  vim.api.nvim_set_hl(0, 'GitSignsChangeNr', { link = 'GitSignsChange' })
  vim.api.nvim_set_hl(0, 'GitSignsChangeLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsChangeInline', { fg = 'none', bg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'GitSignsChangeInlineNr', { link = 'GitSignsChangeInline' })
  vim.api.nvim_set_hl(0, 'GitSignsChangeInlineLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsChangeDelete', { fg = palette.magenta.base, bg = palette.magenta.dim })
  vim.api.nvim_set_hl(0, 'GitSignsChangeDeleteNr', { link = 'GitSignsChangeDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsChangeDeleteLn', { fg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedAdd', { fg = palette.fg.dim, bg = palette.bg.base })
  vim.api.nvim_set_hl(0, 'GitSignsStagedAddNr', { link = 'GitSignsStagedAdd' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedAddLn', { fg = 'none', bg = palette.bg.base })
  vim.api.nvim_set_hl(0, 'GitSignsStagedDelete', { fg = palette.fg.dim, bg = palette.bg.base })
  vim.api.nvim_set_hl(0, 'GitSignsStagedDeleteNr', { link = 'GitSignsStagedDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedTopDelete', { link = 'GitSignsStagedDelete' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedTopDeleteNr', { link = 'GitSignsStagedDeleteNr' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChange', { fg = palette.fg.dim, bg = palette.bg.base })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChangeNr', { link = 'GitSignsStagedChange' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChangeLn', { fg = 'none', bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChangeDelete', { link = 'GitSignsStagedChange' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChangeDeleteNr', { link = 'GitSignsStagedChangeNr' })
  vim.api.nvim_set_hl(0, 'GitSignsStagedChangeDeleteLn', { link = 'GitSignsStagedChangeLn' })
  vim.api.nvim_set_hl(0, 'GitSignsCurrentLineBlame', { fg = palette.fg.dim, bg = palette.bg.dim, italic = true })

  vim.api.nvim_set_hl(0, 'CmpGhostText', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'CmpDocumentation', { fg = palette.fg.base, bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'CmpDocumentationBorder', { fg = palette.sel.dim, bg = palette.bg.dim })
  vim.api.nvim_set_hl(0, 'CmpItemMenu', { link = 'Comment' })
  vim.api.nvim_set_hl(0, 'CmpItemAbbr', { fg = palette.fg.base })
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { link = 'CmpItemAbbrMatch' })
  vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { fg = palette.fg.dim, strikethrough = true })
  vim.api.nvim_set_hl(0, 'CmpItemKind', { fg = palette.fg.dim })
  vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindFile', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindField', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindModule', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindDirectory', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { link = 'CmpItemKind' })
  vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { link = 'Constant' })
  vim.api.nvim_set_hl(0, 'CmpItemKindReference', { link = 'Keyword' })
  vim.api.nvim_set_hl(0, 'CmpItemKindValue', { link = 'Keyword' })
  vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { link = 'Function' })
  vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { link = 'Constant' })
  vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { link = 'Constant' })
  vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { link = 'Constant' })
  vim.api.nvim_set_hl(0, 'CmpItemKindClass', { link = 'Type' })
  vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { link = 'Type' })
  vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { link = 'Identifier' })
  vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { link = 'Operator' })
  vim.api.nvim_set_hl(0, 'CmpItemKindDefault', { link = 'CmpItemKind' })

  vim.api.nvim_set_hl(0, '@variable.member.ledger', { link = '@property' })
  vim.api.nvim_set_hl(0, '@number.ledger', { fg = palette.green.base })
  vim.api.nvim_set_hl(0, '@number.negative.ledger', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, '@markup.raw.ledger', { fg = palette.fg.dimmer })
  vim.api.nvim_set_hl(0, '@string.special.ledger', { fg = palette.pink.base, bold = true })

  vim.api.nvim_set_hl(0, 'TodoBgFIX', { fg = palette.bg.base, bg = palette.red.base })
  vim.api.nvim_set_hl(0, 'TodoFgFIX', { fg = palette.red.base })
  vim.api.nvim_set_hl(0, 'TodoBgTODO', { fg = palette.bg.base, bg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'TodoFgTODO', { fg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'TodoBgHACK', { fg = palette.bg.base, bg = palette.red.base })
  vim.api.nvim_set_hl(0, 'TodoFgHACK', { fg = palette.red.base, bg = 'none' })
  vim.api.nvim_set_hl(0, 'TodoBgWARN', { fg = palette.bg.base, bg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'TodoFgWARN', { fg = palette.yellow.base })
  vim.api.nvim_set_hl(0, 'TodoBgPERF', { fg = palette.bg.base, bg = palette.cyan.base })
  vim.api.nvim_set_hl(0, 'TodoFgPERF', { fg = palette.cyan.base })
  vim.api.nvim_set_hl(0, 'TodoBgNOTE', { fg = palette.bg.base, bg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'TodoFgNOTE', { fg = palette.magenta.base })
  vim.api.nvim_set_hl(0, 'TodoBgTEST', { fg = palette.bg.base, bg = palette.cyan.base })
  vim.api.nvim_set_hl(0, 'TodoFgTEST', { fg = palette.cyan.base })

  vim.api.nvim_set_hl(0, 'ExchangeRegion', { fg = palette.bg.base, bg = palette.orange.base })

  vim.api.nvim_set_hl(0, 'Cursorword', { fg = palette.bg.base, bg = palette.accent.base })

  local _, lualine = pcall(require, 'lualine')
  if lualine then
    local normal = {
      a = { fg = palette.bg.base, bg = palette.fg.base },
      b = { fg = palette.bg.base, bg = palette.fg.dim },
      c = { fg = palette.fg.dim, bg = palette.bg.dim },
    }
    local command = {
      a = { fg = palette.bg.base, bg = palette.pink.base },
      b = { fg = palette.fg.base, bg = palette.pink.dim },
      c = { fg = palette.fg.dim, bg = palette.bg.dim },
    }

    lualine.setup({
      options = {
        theme = {
          normal = normal,
          insert = {
            a = { fg = palette.bg.base, bg = palette.green.base },
            b = { fg = palette.fg.base, bg = palette.green.dim },
            c = { fg = palette.fg.dim, bg = palette.bg.dim },
          },
          command = command,
          visual = {
            a = { fg = palette.bg.base, bg = palette.blue.base },
            b = { fg = palette.fg.base, bg = palette.blue.dim },
            c = { fg = palette.fg.dim, bg = palette.bg.dim },
          },
          replace = {
            a = { fg = palette.bg.base, bg = palette.red.base },
            b = { fg = palette.fg.base, bg = palette.red.dim },
            c = { fg = palette.fg.dim, bg = palette.bg.dim },
          },
          terminal = command,
          inactive = normal,
        }
      }
    })
  end

  local _, devicons = pcall(require, 'nvim-web-devicons')
  if devicons then devicons.set_default_icon('', palette.fg.dim, 0) end
end
